[package]
name = "proof-builder-rpc"
version.workspace = true
edition.workspace = true

[[bin]]
name = "proof-builder-rpc"
path = "src/main.rs"

[dependencies]
zkm-sdk = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
dotenv = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
store = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
axum = { workspace = true, features = ["macros", "json"] }
http-body-util.workspace = true
prometheus-client = { workspace = true }
uuid = { workspace = true }
bitcoin = { workspace = true }
secp256k1 = { workspace = true }
strum = { workspace = true }
serde_json = { workspace = true }
alloy-primitives = { workspace = true }

# proofs
proof-builder = { workspace = true }
header-chain-proof = { workspace = true }
commit-chain-proof = { workspace = true }
commit-chain = { workspace = true }
state-chain-proof = { workspace = true }
watchtower-proof = { workspace = true }
operator-proof = { workspace = true }
util = { workspace = true }
client = { workspace = true }
bitcoin-light-client-circuit.workspace = true

#config
toml.workspace = true
tower-http = { version = "0.6.2", features = ["cors", "trace"] }

[lints]
workspace = true
