[package]
name = "commit-chain-proof"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
hex.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
dotenv.workspace = true
sha2.workspace = true
serde_json.workspace = true

commit-chain = { workspace = true }
bitcoin = { workspace = true }
client = { workspace = true }
tendermint = { workspace = true, default-features = false }
tendermint-light-client-verifier = { workspace = true, default-features = false, features = [
  "rust-crypto",
] }

proof-builder.workspace = true
zkm-version.workspace = true

# Ziren
zkm-sdk.workspace = true
zkm-prover.workspace = true

[build-dependencies]
zkm-build.workspace = true
