[package]
name = "operator-wrapper-proof"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bitcoin = { workspace = true, features = ["serde", "rand", "secp-recovery"] }
bitcoin-light-client-circuit = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
dotenv.workspace = true
hex.workspace = true
proof-builder.workspace = true
serde.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["max_level_trace"] }
tracing-subscriber.workspace = true
zkm-primitives.workspace = true
zkm-prover.workspace = true
zkm-sdk.workspace = true

[build-dependencies]
zkm-build.workspace = true
