[package]
name = "proof-builder"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
serde.workspace = true

# Ziren
zkm-sdk.workspace = true
#zkm-prover.workspace = true
#zkm-verifier.workspace = true
strum = { workspace = true, features = ["derive"] }

#
header-chain.workspace = true
commit-chain.workspace = true
#bitcoin-light-client-circuit.workspace = true
state-chain.workspace = true
bitcoin = { workspace = true }

[lints]
workspace = true
