[package]
name = "bitvm2-noded"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bitvm2-noded"
path = "src/main.rs"

[[bin]]
name = "pegin-request"
path = "src/bin/send_pegin_request.rs"

[[bin]]
name = "challenge"
path = "src/bin/send_challenge.rs"

[[bin]]
name = "sequencer-set-publish"
path = "src/bin/sequencer-set-publish.rs"

[[bin]]
name = "send-rbf"
path = "src/bin/send_rbf.rs"

[[bin]]
name = "update-db"
path = "src/bin/db_inject.rs"

[dependencies]
libp2p = { workspace = true, features = [
    "autonat",
    "dns",
    "tokio",
    "noise",
    "tcp",
    "yamux",
    "identify",
    "kad",
    "ping",
    "relay",
    "metrics",
    "rsa",
    "macros",
    "gossipsub",
    "quic",
    "websocket",
] }
libp2p-swarm-derive = { workspace = true }
libp2p-metrics = { workspace = true }
zeroize = { workspace = true }

clap = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
indexmap = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
dotenv = { workspace = true }
strum = { workspace = true }
tendermint = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true

http-body-util.workspace = true
axum = { workspace = true, features = ["macros", "json"] }
reqwest = { workspace = true, features = ["json"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
http = { workspace = true }
stun-client = "0.1.4"
prometheus-client = { workspace = true }
esplora-client = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
thiserror = "2.0"

bitcoin = { workspace = true, features = ["serde"] }
bitcoin-script = { workspace = true }
alloy = { workspace = true, features = ["full", "serde"] }

secp256k1 = { workspace = true }
sha2 = { workspace = true }
musig2 = { workspace = true }
ark-serialize = { workspace = true }
once_cell = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }

indicatif = "0.17.8"
dirs = "5.0.1"

zkm-sdk = { workspace = true }
zkm-verifier = { workspace = true }
borsh = {version = "1.5.3", features = ["derive"] }

proof-builder = { workspace = true }
util = { workspace = true }
bitvm = { workspace = true }
goat = { workspace = true }
bitvm2-lib = { workspace = true }
store = { workspace = true }
client = { workspace = true }
bitcoin-light-client-circuit = { workspace = true }
commit-chain = { workspace = true }
cbft-rpc = { workspace = true }

[dev-dependencies]
serial_test = "3.2"
regex = "1.11"
scopeguard = "1.2"
