[package]
name = "protocol-model"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[[bin]]
name = "protocol-model"
path = "src/bin/protocol-model.rs"
