[package]
name = "store"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = {  version = "0.8.3", features = [ "sqlite", "runtime-tokio", "uuid", "json"] }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
uuid = { workspace = true }
bitcoin = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
protocol-model = { workspace = true }
tracing = { workspace = true }

futures = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["multipart", "json", "stream"]}
serde_json = { workspace = true }
walkdir = "2"
tokio-util.workspace = true

[dev-dependencies]
tempfile = "3.19.1"
